#!/usr/bin/env node
// Build pipeline for lily-design-system-svelte-headless.
//
//   1. Generate `index.ts` — the public barrel re-exporting every
//      `components/<Name>/<Name>.svelte`. Generated, not hand-maintained:
//      the catalog is ~491 components and grows.
//   2. Stage the runtime sources into a throwaway directory and run
//      svelte-package over it, emitting `dist/`.
//
// The staging step exists because svelte-package copies *everything* in its
// input directory and has no ignore mechanism. Each component directory
// holds its test, its Storybook story and its docs alongside the component,
// and none of those belong in the tarball. This mirrors the same staging
// trick the svelte-helpers catalog uses.
//
// Why this exists: until 0.3.0 the package declared `"main": "index.js"`
// and no such file was ever built, so importing the package failed at
// resolution for every consumer.

import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));
const componentsDir = path.join(root, "components");
const stageDir = path.join(root, ".svelte-package-src");
const distDir = path.join(root, "dist");

// A component is a directory holding a `.svelte` file of the same name.
// Everything else in `components/` — `.claude/`, a stray `node_modules/`
// Vite cache — is not a component and must not reach the barrel.
const names = fs
  .readdirSync(componentsDir, { withFileTypes: true })
  .filter(
    (entry) =>
      entry.isDirectory() &&
      fs.existsSync(path.join(componentsDir, entry.name, `${entry.name}.svelte`)),
  )
  .map((entry) => entry.name)
  .sort();

if (names.length === 0) {
  throw new Error(`No components found in ${componentsDir}.`);
}

const barrel =
  "// Generated by build.mjs — do not edit by hand.\n" +
  "// Barrel export of every component in the Lily Design System catalog.\n\n" +
  names
    .map(
      (name) =>
        `export { default as ${name} } from "./components/${name}/${name}.svelte";`,
    )
    .join("\n") +
  "\n";

fs.writeFileSync(path.join(root, "index.ts"), barrel);
console.log(`generated index.ts (${names.length} components)`);

fs.rmSync(stageDir, { recursive: true, force: true });
fs.rmSync(distDir, { recursive: true, force: true });
fs.mkdirSync(path.join(stageDir, "components"), { recursive: true });
fs.writeFileSync(path.join(stageDir, "index.ts"), barrel);

for (const name of names) {
  const target = path.join(stageDir, "components", name);
  fs.mkdirSync(target, { recursive: true });
  fs.copyFileSync(
    path.join(componentsDir, name, `${name}.svelte`),
    path.join(target, `${name}.svelte`),
  );
}

try {
  execFileSync(
    "npx",
    ["--yes", "@sveltejs/package@2.5.8", "-i", stageDir, "-o", distDir],
    { cwd: root, stdio: "inherit" },
  );
} finally {
  fs.rmSync(stageDir, { recursive: true, force: true });
  // svelte-package leaves its d.ts temp dir next to cwd.
  fs.rmSync(path.join(root, ".svelte-kit"), { recursive: true, force: true });
}

for (const artifact of ["index.js", "index.d.ts"]) {
  const file = path.join(distDir, artifact);
  if (!fs.existsSync(file) || fs.statSync(file).size === 0) {
    throw new Error(`expected a non-empty dist/${artifact} after build.`);
  }
}
console.log("build ok");
